<img height="60px" src="https://colab.research.google.com/img/colab_favicon.ico" align="left" hspace="20px" vspace="5px">

# Q-Table Learning

* References:

[https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0](https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0)

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/learning-stack/Colab-ML-Playbook/blob/master/Reinforcement%20Learning/Simple%20Reinforcement%20Learning%20with%20Tensorflow/Part%200-Q-Table%20Learning-Clean.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/learning-stack/Colab-ML-Playbook/blob/master/Reinforcement%20Learning/Simple%20Reinforcement%20Learning%20with%20Tensorflow/Part%200-Q-Table%20Learning-Clean.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

In [0]:
#installing dependencies
!apt-get -qq -y install libcusparse8.0 libnvrtc8.0 libnvtoolsext1 > /dev/null
!ln -snf /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so.8.0 /usr/lib/x86_64-linux-gnu/libnvrtc-builtins.so
!apt-get -qq -y install xvfb freeglut3-dev ffmpeg> /dev/null
!pip -q install gym
!pip -q install pyglet
!pip -q install pyopengl
!pip -q install pyvirtualdisplay

Extracting templates from packages: 100%


In [0]:
import gym
import numpy as np

### Load the environment

In [0]:
env = gym.make('FrozenLake-v0')

### Implement Q-Table learning algorithm

In [0]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [0]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.485


In [0]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[4.19994367e-01 5.81112250e-03 5.22528105e-03 6.11735683e-03]
 [1.04662603e-03 7.21004928e-04 2.03639719e-04 8.02813506e-02]
 [9.42434195e-02 3.77313787e-03 3.41692595e-03 4.77874253e-03]
 [7.12104557e-04 3.39940614e-03 3.32210834e-03 4.74789319e-03]
 [6.16705717e-01 3.91800661e-03 1.59676751e-03 2.79824363e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.68472529e-03 1.73670571e-04 2.22623581e-05 1.33686738e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.28047501e-04 0.00000000e+00 1.08165616e-03 6.95491342e-01]
 [1.37523413e-03 3.09948389e-01 1.51570238e-03 0.00000000e+00]
 [4.93380950e-02 7.00002539e-04 0.00000000e+00 2.78729755e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.24916681e-01 1.38000746e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.78512756e-01]
 [0.00000000e+00 0.00000000e+00 0.